- id: 'corridor_pir_yaml'
  alias: Light - Corridor
  description: YAML
  trigger:
  - platform: state
    entity_id: binary_sensor.h801_corridor_pir
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    data: {}
    target:
      device_id: f0c707f7f2c746b44076f82683dff955
  mode: single
