- platform: rest
  name: Proxmox
  json_attributes:
    - uptime
    - cpu_temp
    - cpu_core1_temp
    - cpu_core2_temp
    - acpi_temp1
    - acpi_temp2
    - disk_usage
    - homeassistant_vm
  resource: !secret proxmox_data
  value_template: '{{ value_json.status }}'
  scan_interval: 30

- platform: template
  sensors:
    proxmox_cpu_temperature:
      unique_id: proxmox_cpu_temperature
      value_template: '{{ state_attr("sensor.proxmox", "cpu_temp") | float }}'
      device_class: temperature
      unit_of_measurement: "°C"
      friendly_name: Proxmox CPU Temperature
    proxmox_cpu_core1_temperature:
      unique_id: proxmox_cpu_core1_temperature
      value_template: '{{ state_attr("sensor.proxmox", "cpu_core1_temp") | float }}'
      device_class: temperature
      unit_of_measurement: "°C"
      friendly_name: Proxmox CPU Core 1 Temperature
    proxmox_cpu_core2_temperature:
      unique_id: proxmox_cpu_core2_temperature
      value_template: '{{ state_attr("sensor.proxmox", "cpu_core2_temp") | float }}'
      device_class: temperature
      unit_of_measurement: "°C"
      friendly_name: Proxmox CPU Core 2 Temperature
    proxmox_acpi_temp1:
      unique_id: proxmox_acpi_temp1
      value_template: '{{ state_attr("sensor.proxmox", "acpi_temp1") | float }}'
      device_class: temperature
      unit_of_measurement: "°C"
      friendly_name: Proxmox ACPI1 Temperature 
    proxmox_acpi_temp2:
      unique_id: proxmox_acpi_temp2
      value_template: '{{ state_attr("sensor.proxmox", "acpi_temp2") | float }}'
      device_class: temperature
      unit_of_measurement: "°C"
      friendly_name: Proxmox ACPI2 Temperature 
    proxmox_disk_usage:
      unique_id: proxmox_disk_usage
      value_template: '{{ state_attr("sensor.proxmox", "disk_usage") | float }}'
      unit_of_measurement: "%"
      friendly_name: Proxmox Disk Usage